// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKvNJVWdxJIt2kBSgNGhAwF6NvY5NB43E',
    appId: '1:700191840421:web:1f69e1556d71da1f88154c',
    messagingSenderId: '700191840421',
    projectId: 'xiii-79931',
    authDomain: 'xiii-79931.firebaseapp.com',
    storageBucket: 'xiii-79931.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1zM9tYhpF5C0XSFKesXx0SS8ppbqfzUw',
    appId: '1:700191840421:android:73d6f6b52f2881f988154c',
    messagingSenderId: '700191840421',
    projectId: 'xiii-79931',
    storageBucket: 'xiii-79931.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-C5qee1kAikhx6-AEv6-4rqLyLXnEZw',
    appId: '1:700191840421:ios:272007d37c24f96188154c',
    messagingSenderId: '700191840421',
    projectId: 'xiii-79931',
    storageBucket: 'xiii-79931.firebasestorage.app',
    iosClientId: '700191840421-kj31d7fpg10smkpofbpqrpdpjrm3te9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP-C5qee1kAikhx6-AEv6-4rqLyLXnEZw',
    appId: '1:700191840421:ios:272007d37c24f96188154c',
    messagingSenderId: '700191840421',
    projectId: 'xiii-79931',
    storageBucket: 'xiii-79931.firebasestorage.app',
    iosClientId: '700191840421-kj31d7fpg10smkpofbpqrpdpjrm3te9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKvNJVWdxJIt2kBSgNGhAwF6NvY5NB43E',
    appId: '1:700191840421:web:a62cc31061cede7e88154c',
    messagingSenderId: '700191840421',
    projectId: 'xiii-79931',
    authDomain: 'xiii-79931.firebaseapp.com',
    storageBucket: 'xiii-79931.firebasestorage.app',
  );
}
